import { ReactNode } from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navigation/Navbar';

type LayoutProps = {
  children: ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full xl:container flex-col min-h-screen">
        <Navbar />

        <div className="mt-5">{children}</div>

        <footer className="flex justify-center items-center w-full h-16 bg-pink mt-auto">
          <span className="text-sm">All rights reserved</span>
        </footer>
      </main>
    </div>
  );
}
