import { ReactNode } from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navigation/Navbar';

type LayoutProps = {
  children: ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen w-full flex-col xl:container">
        <Navbar />

        <div className="z-[1] mt-5 flex flex-auto">{children}</div>

        <footer className="mt-auto flex h-16 w-full items-center justify-center bg-pink">
          <span className="text-sm">All rights reserved</span>
        </footer>
      </main>
    </div>
  );
}
