import { ReactNode } from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navigation/Navbar';
import Link from 'next/link';
import { routes as appRoutes } from '@/routes';
import Image from 'next/image';
import Logo from '@/assets/images/Logo.svg';

type LayoutProps = {
  children: ReactNode;
};

export default function LoginLayout({ children }: LayoutProps) {
  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full xl:container flex-col min-h-screen">
        <header className="navbar bg-base-100 pt-12 px-12 relative">
          <div className="w-full bg-no-repeat  h-[782px] max-w-[1440px] -z-10 absolute left-0 top-0 bg-grayBg bg-cover" />
          <div className="flex-1">
            <Link className="h-6 normal-case text-xl relative w-32 disabled:hover" href={appRoutes.home}>
              <Image fill src={Logo} alt="meetApp logo" />
            </Link>
          </div>
        </header>

        <div className="flex mt-5 flex-auto">{children}</div>

        <footer className="flex justify-center items-center w-full h-16 bg-pink mt-auto">
          <span className="text-sm">All rights reserved</span>
        </footer>
      </main>
    </div>
  );
}
