import { ReactNode } from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navigation/Navbar';
import Link from 'next/link';
import { routes as appRoutes } from '@/utils/routes';
import Image from 'next/image';
import Logo from '@/assets/images/Logo.svg';

type LayoutProps = {
  children: ReactNode;
};

export default function LoginLayout({ children }: LayoutProps) {
  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen w-full flex-col xl:container">
        <header className="navbar relative bg-base-100 bg-transparent px-12 pt-12">
          <div className="absolute left-0  top-0 -z-10 h-[782px] w-full max-w-[1440px] bg-grayBg bg-cover bg-no-repeat" />
          <div className="flex-1">
            <Link className="relative h-6 w-32 text-xl normal-case disabled:hover" href={appRoutes.home}>
              <Image fill src={Logo} alt="meetApp logo" />
            </Link>
          </div>
        </header>

        <div className="mt-5 flex flex-auto">{children}</div>

        <footer className="mt-auto flex h-16 w-full items-center justify-center bg-pink">
          <span className="text-sm">All rights reserved</span>
        </footer>
      </main>
    </div>
  );
}
